# Large base image
FROM python:3.10

WORKDIR /app

# Copy everything (bad practice)
COPY . .

# Install dependencies
RUN pip install -r requirements.txt

# Streamlit runs on port 8501
EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
